name: docker workflow
on:
  push:
    branches:
      - main
jobs:
    docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: login in docker
              run: docker login
            - name: Image from docker hub
              run: docker pull mtaori/myloginform:v1
            # - name: build image
            #   run: docker build . -t mtaori/myloginform:v1
            #   working-directory: /home/runner/work/gh-workflows/gh-workflows/third-project
            - name: run image
              run: docker run -itd -p 6010:80 mtaori/myloginform:v1
            #   working-directory: /home/runner/work/gh-workflows/gh-workflows/third-project
            
    show-image:
        needs: docker-image
        runs-on: ubuntu-latest
        steps: 
            - name: show container
              run: docker ps -a

            - name: Get public IP address
              run: |
                echo "Waiting for the server to start..."
                PUBLIC_IP=$(curl -s ifconfig.me)
                echo "Public IP: $PUBLIC_IP"
                echo "Access the app here: http://$PUBLIC_IP:6010"
        

            